In [1]:
# importer la blibliothèque numpy comme s'appelant np qu'on utilisera 
# dans le code
import numpy as np

In [2]:
# ndarray ne contiennent que le même type: int str, liste... mais modifiables
# création d'un tableau à partir d'une liste
np.array([12,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

array([12,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [3]:
# ranger dans une variable notre_tableau à une dimension, un vecteur
#  le typage array permet de faire des manipulations très performantes
notre_tableau=np.array([12,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [4]:
# création tableau à 2 dimensions (lignes et colonnes)
# on passe une liste de liste [[],[],[]...] séparées par des virgules
tableau_array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
tableau_array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Vue et copies de tableaux
# tableau contenant les 5 premières valeurs de notre tableau en utilisant index
sous_tableau=notre_tableau[0:5]
sous_tableau

array([12,  3,  4,  5,  6])

In [6]:
# pour ne pas faire une vue qui signifie que les modifications se répercutent 
# sur le tableau origine, on utilise .copy()
sous_tableau=notre_tableau[0:5].copy()
sous_tableau

array([12,  3,  4,  5,  6])

In [7]:
# modification du sous_tableau
sous_tableau[0]=10
print(sous_tableau) # modifié premier élément passé de 12 à 10 : copie
print(notre_tableau) # non modifié :premier élément 10 non modifié en 12

[10  3  4  5  6]
[12  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [8]:
# comment accéder aux éléments d'un array à 2 dimensions
# et comment faire du slicing sur un tableau à 2 dimensions
# on doit utiliser 2 index, un pour les lignes, un pour les colonnes

# création tableau à 2 dimensions (lignes et colonnes)
# on passe une liste de liste [[],[],[]...] séparées par des virgules
tableau_array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
tableau_array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# utilisation de 2 index ligne2 colonne 3 narray[index_ligne, index_colonne]
tableau_array_2d[1,2] # valeur de 2ieme ligne 3ieme colonne

6

In [10]:
# on peut utiliser des index négatifs
tableau_array_2d[1,-1]

6

In [11]:
# slicing
# première colonne et toutes les lignes de la première colonne (:)
tableau_array_2d[:,0]

array([1, 4, 7])

In [12]:
# afficher une ligne entière : toute les colonnes de la première ligne
tableau_array_2d[0,:]

array([1, 2, 3])

In [13]:
# afficher toutes les lignes (:) et les colonnes  1,2 ,3 [0:3: pas] d'un pas 2
tableau_array_2d[:,0:3:2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [14]:
# pour partir de la fin ==> négatif 
# toutes les lignes et dernière colonne
tableau_array_2d[:,-1]

array([3, 6, 9])

In [15]:
# on veut aller d'un entier positif à un entier négatif
# 2ième colonne
tableau_array_2d[:,1:-1]

array([[2],
       [5],
       [8]])

In [16]:
#  que la ligne 2 de la deuxième colonne
tableau_array_2d[2,1:-1]

array([8])

In [17]:
# comment filtrer un array bidimensionnel, ne garder que quelques valeurs...

# création objet array, alimenté alétoirement avec sous-modules randint
# de random de la librairie numpy
# valeur maxi des valeurs=100 : 0 à 100
# taille de 6 lignes 4 colonnes
array=np.random.randint(100, size=(6,4))
array

array([[60, 82, 21, 10],
       [81, 26, 39, 37],
       [89, 21, 66, 18],
       [55, 41, 61, 14],
       [73, 72, 97, 28],
       [93, 57, 50, 61]])

In [18]:
# comment utiliser les attributs de la classe array
# ndarray est une classe ==> objet particulier
# voir manuel de référence de scipy
# utilisation de l'attribut ndim : nombre dimension de l'array : 2 dimensions
array.ndim


2

In [19]:
# nombre lignes et colonnes : 6 lignes, 4 colonnes
array.shape

(6, 4)

In [20]:
# type de l'array ==> int32
array.dtype

dtype('int32')

In [21]:
# taille de notre tableau=nombre valeur du tableau : 24 valeurs
array.size

24

In [22]:
# filtrer les array grâce à des booleen
# ne conserver que les valeurs de l'array supérieurs à 50
# sélection que des valeurs pour lesquelles les conditions sont True
array[array>50]

array([60, 82, 81, 89, 66, 55, 61, 73, 72, 97, 93, 57, 61])

In [23]:
#  il fait une boucle et répond à la condition > True non False
array>50

array([[ True,  True, False, False],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True,  True,  True, False],
       [ True,  True, False,  True]])

In [24]:
array[array>=50]

array([60, 82, 81, 89, 66, 55, 61, 73, 72, 97, 93, 57, 50, 61])

In [25]:
array[array<50]

array([21, 10, 26, 39, 37, 21, 18, 41, 14, 28])

In [26]:
array[array == 50]

array([50])

In [27]:
array[array != 50]

array([60, 82, 21, 10, 81, 26, 39, 37, 89, 21, 66, 18, 55, 41, 61, 14, 73,
       72, 97, 28, 93, 57, 61])

In [28]:
# opérateurs logiques 
# & : and
# | : or
array[(array>=50) & (array<= 70)]

array([60, 66, 55, 61, 57, 50, 61])

In [29]:
# OU logique
array[(array>=50) | (array <= 40)]

array([60, 82, 21, 10, 81, 26, 39, 37, 89, 21, 66, 18, 55, 61, 14, 73, 72,
       97, 28, 93, 57, 50, 61])

In [30]:
# concaténation de tableau avec numpy , jointure de 2 tableaux
# création de 2 arrays
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2=np.array([[2,5,6],[9,10,11],[5,6,9]])

In [31]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
array2

array([[ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9]])

In [33]:
#  si tableaux de même dimension, on peut les concaténer
np.concatenate([array1,array2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9]])

In [34]:
#  création nouveau tableau
array3=np.array([[4,10,13],[7,14,15],[10,16,84]])

In [35]:
array3

array([[ 4, 10, 13],
       [ 7, 14, 15],
       [10, 16, 84]])

In [36]:
np.concatenate([array1,array2, array3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9],
       [ 4, 10, 13],
       [ 7, 14, 15],
       [10, 16, 84]])

In [37]:
# pour des tableaux de dimension différentes
# on utilise fonction vstak empilation verticale
# on utilise fonction vstak empilation horizontale
# création tableau à une dimension
array4=np.array([15,16,47])

In [38]:
array4

array([15, 16, 47])

In [39]:
# création tableau à 2 dimensions de 3 lignes 3 colonnes 
array5=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [40]:
array5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# pour ajouter une ligne
# empilation verticale car on ajoute une ligne
# ==> vstack array4 en premier puis array5
array6=np.vstack([array4,array5])

In [45]:
array6

array([[15, 16, 47],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [46]:
# pour ajouter une colonne
# empilation horizontale car on ajoute une colonne
# ==> hstack 
array7=np.array([[15],[16],[47]])

In [47]:
array7

array([[15],
       [16],
       [47]])

In [48]:
# première colonne array7, deuxième colonne array5
array8=np.hstack([array7,array5])

In [49]:
array8

array([[15,  1,  2,  3],
       [16,  4,  5,  6],
       [47,  7,  8,  9]])

In [50]:
# comment spliter ou casser un array avec numpy
# contraire de la concaténation on veut le découper

# SPLIT d'un tableau MONODIMENSIONNELLE
# création array à une dimension
array9=np.array([15,16,17,12,49,52,12,14,36])

In [51]:
array9

array([15, 16, 17, 12, 49, 52, 12, 14, 36])

In [52]:
# taille de l'array
len(array9)

9

In [53]:
# on veut casser le tableau en 3
# on utilise split en lui envoyant les points de cassures 
# point de cassure 2 = index où on veut casser le dossier (commence par 0)
array10=np.split(array9,[2,6])

In [54]:
array10

[array([15, 16]), array([17, 12, 49, 52]), array([12, 14, 36])]

In [55]:
# on obtient une liste de 3 array
array11,array12,array13=array10

In [56]:
array11

array([15, 16])

In [57]:
array12

array([17, 12, 49, 52])

In [58]:
array13

array([12, 14, 36])

In [59]:
print(array11,array12,array13)

[15 16] [17 12 49 52] [12 14 36]


In [60]:
# pour spliter en 4 un tableau impair à la fin il prend le reste
array21,array22,array23,array24=np.split(array9,[2,4,6])
print(array21,array22,array23,array24)

[15 16] [17 12] [49 52] [12 14 36]


In [61]:
# SPLIT D'UN TABLEAU A 2 DIMENSIONS
# création du tableau à 2 dimensions
array30=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
array30

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
array31, array32=np.vsplit(array30,[2])
print(array31,array32)

[[1 2 3]
 [4 5 6]] [[7 8 9]]


In [68]:
array30

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
array33, array34=np.hsplit(array30,[2])
print(array33,array34)

[[1 2]
 [4 5]
 [7 8]] [[3]
 [6]
 [9]]


In [69]:
# les calculs sur les array
# création tableau avec valeur aléatoires
array=np.random.randint(350, size=(10,9))

In [70]:
array

array([[320, 111,  48,  53,  18,  19,  80,  39, 199],
       [286, 156, 284,  12, 140, 222, 281,  57,  21],
       [ 88, 277, 296, 178, 263, 103,  33, 349,  50],
       [187,  24, 297, 315,  34, 260, 234,  75,  41],
       [263, 272, 176, 129,  68, 319,   3, 267, 161],
       [138, 206,  47, 133, 275, 144, 105, 167,  68],
       [ 99, 139, 102,  75, 145,  13,  54,  74, 199],
       [131, 288, 192, 284,  73,  45, 285, 147, 145],
       [281, 152, 292, 163,  66,  95,  73, 218,  72],
       [186, 209, 255, 137, 210,  82, 199, 309,  69]])

In [71]:
# ajouter une valeur à tous les éléments d'un array
# ajouter +2 à toutes les valeurs array+2
array+2

array([[322, 113,  50,  55,  20,  21,  82,  41, 201],
       [288, 158, 286,  14, 142, 224, 283,  59,  23],
       [ 90, 279, 298, 180, 265, 105,  35, 351,  52],
       [189,  26, 299, 317,  36, 262, 236,  77,  43],
       [265, 274, 178, 131,  70, 321,   5, 269, 163],
       [140, 208,  49, 135, 277, 146, 107, 169,  70],
       [101, 141, 104,  77, 147,  15,  56,  76, 201],
       [133, 290, 194, 286,  75,  47, 287, 149, 147],
       [283, 154, 294, 165,  68,  97,  75, 220,  74],
       [188, 211, 257, 139, 212,  84, 201, 311,  71]])

In [72]:
# enlever une valeur à toutes les valeurs du tableau
array - 2

array([[318, 109,  46,  51,  16,  17,  78,  37, 197],
       [284, 154, 282,  10, 138, 220, 279,  55,  19],
       [ 86, 275, 294, 176, 261, 101,  31, 347,  48],
       [185,  22, 295, 313,  32, 258, 232,  73,  39],
       [261, 270, 174, 127,  66, 317,   1, 265, 159],
       [136, 204,  45, 131, 273, 142, 103, 165,  66],
       [ 97, 137, 100,  73, 143,  11,  52,  72, 197],
       [129, 286, 190, 282,  71,  43, 283, 145, 143],
       [279, 150, 290, 161,  64,  93,  71, 216,  70],
       [184, 207, 253, 135, 208,  80, 197, 307,  67]])

In [73]:
# multiplier une valeur à toutes les valeurs du tableau
array * 10

array([[3200, 1110,  480,  530,  180,  190,  800,  390, 1990],
       [2860, 1560, 2840,  120, 1400, 2220, 2810,  570,  210],
       [ 880, 2770, 2960, 1780, 2630, 1030,  330, 3490,  500],
       [1870,  240, 2970, 3150,  340, 2600, 2340,  750,  410],
       [2630, 2720, 1760, 1290,  680, 3190,   30, 2670, 1610],
       [1380, 2060,  470, 1330, 2750, 1440, 1050, 1670,  680],
       [ 990, 1390, 1020,  750, 1450,  130,  540,  740, 1990],
       [1310, 2880, 1920, 2840,  730,  450, 2850, 1470, 1450],
       [2810, 1520, 2920, 1630,  660,  950,  730, 2180,  720],
       [1860, 2090, 2550, 1370, 2100,  820, 1990, 3090,  690]])

In [75]:
# opérations arithmétiques par colonne ou ligne

# Ex: multiplier la première colonne uniquement par 10
array[:,0] * 10

array([3200, 2860,  880, 1870, 2630, 1380,  990, 1310, 2810, 1860])

In [76]:
# diviser toutes les valeurs 
array / 2

array([[160. ,  55.5,  24. ,  26.5,   9. ,   9.5,  40. ,  19.5,  99.5],
       [143. ,  78. , 142. ,   6. ,  70. , 111. , 140.5,  28.5,  10.5],
       [ 44. , 138.5, 148. ,  89. , 131.5,  51.5,  16.5, 174.5,  25. ],
       [ 93.5,  12. , 148.5, 157.5,  17. , 130. , 117. ,  37.5,  20.5],
       [131.5, 136. ,  88. ,  64.5,  34. , 159.5,   1.5, 133.5,  80.5],
       [ 69. , 103. ,  23.5,  66.5, 137.5,  72. ,  52.5,  83.5,  34. ],
       [ 49.5,  69.5,  51. ,  37.5,  72.5,   6.5,  27. ,  37. ,  99.5],
       [ 65.5, 144. ,  96. , 142. ,  36.5,  22.5, 142.5,  73.5,  72.5],
       [140.5,  76. , 146. ,  81.5,  33. ,  47.5,  36.5, 109. ,  36. ],
       [ 93. , 104.5, 127.5,  68.5, 105. ,  41. ,  99.5, 154.5,  34.5]])

In [77]:
# fonction add : performante et optimiser pour ajouter
np.add(array,2)

array([[322, 113,  50,  55,  20,  21,  82,  41, 201],
       [288, 158, 286,  14, 142, 224, 283,  59,  23],
       [ 90, 279, 298, 180, 265, 105,  35, 351,  52],
       [189,  26, 299, 317,  36, 262, 236,  77,  43],
       [265, 274, 178, 131,  70, 321,   5, 269, 163],
       [140, 208,  49, 135, 277, 146, 107, 169,  70],
       [101, 141, 104,  77, 147,  15,  56,  76, 201],
       [133, 290, 194, 286,  75,  47, 287, 149, 147],
       [283, 154, 294, 165,  68,  97,  75, 220,  74],
       [188, 211, 257, 139, 212,  84, 201, 311,  71]])

In [78]:
# fonction substract soustraire
np.subtract(array,7)

array([[313, 104,  41,  46,  11,  12,  73,  32, 192],
       [279, 149, 277,   5, 133, 215, 274,  50,  14],
       [ 81, 270, 289, 171, 256,  96,  26, 342,  43],
       [180,  17, 290, 308,  27, 253, 227,  68,  34],
       [256, 265, 169, 122,  61, 312,  -4, 260, 154],
       [131, 199,  40, 126, 268, 137,  98, 160,  61],
       [ 92, 132,  95,  68, 138,   6,  47,  67, 192],
       [124, 281, 185, 277,  66,  38, 278, 140, 138],
       [274, 145, 285, 156,  59,  88,  66, 211,  65],
       [179, 202, 248, 130, 203,  75, 192, 302,  62]])

In [79]:
# fonction multiply : pour multiplier
np.multiply(array,10)

array([[3200, 1110,  480,  530,  180,  190,  800,  390, 1990],
       [2860, 1560, 2840,  120, 1400, 2220, 2810,  570,  210],
       [ 880, 2770, 2960, 1780, 2630, 1030,  330, 3490,  500],
       [1870,  240, 2970, 3150,  340, 2600, 2340,  750,  410],
       [2630, 2720, 1760, 1290,  680, 3190,   30, 2670, 1610],
       [1380, 2060,  470, 1330, 2750, 1440, 1050, 1670,  680],
       [ 990, 1390, 1020,  750, 1450,  130,  540,  740, 1990],
       [1310, 2880, 1920, 2840,  730,  450, 2850, 1470, 1450],
       [2810, 1520, 2920, 1630,  660,  950,  730, 2180,  720],
       [1860, 2090, 2550, 1370, 2100,  820, 1990, 3090,  690]])

In [80]:
# fonction divide : pour diviser
np.divide(array,50)

array([[6.4 , 2.22, 0.96, 1.06, 0.36, 0.38, 1.6 , 0.78, 3.98],
       [5.72, 3.12, 5.68, 0.24, 2.8 , 4.44, 5.62, 1.14, 0.42],
       [1.76, 5.54, 5.92, 3.56, 5.26, 2.06, 0.66, 6.98, 1.  ],
       [3.74, 0.48, 5.94, 6.3 , 0.68, 5.2 , 4.68, 1.5 , 0.82],
       [5.26, 5.44, 3.52, 2.58, 1.36, 6.38, 0.06, 5.34, 3.22],
       [2.76, 4.12, 0.94, 2.66, 5.5 , 2.88, 2.1 , 3.34, 1.36],
       [1.98, 2.78, 2.04, 1.5 , 2.9 , 0.26, 1.08, 1.48, 3.98],
       [2.62, 5.76, 3.84, 5.68, 1.46, 0.9 , 5.7 , 2.94, 2.9 ],
       [5.62, 3.04, 5.84, 3.26, 1.32, 1.9 , 1.46, 4.36, 1.44],
       [3.72, 4.18, 5.1 , 2.74, 4.2 , 1.64, 3.98, 6.18, 1.38]])

In [81]:
# calculer la moyenne des valeurs : fonction mean
np.mean(array)

154.98888888888888

In [82]:
# calculer la moyenne avec une méthode mean spécifique au array
array.mean()

154.98888888888888

In [83]:
# valeur minimum du tableau
array.min()

3

In [84]:
# valeur maximum du tableau
array.max()

349

In [85]:
# calculer la moyenne par colonne avec axis=0
np.mean(array, axis=0)

array([197.9, 183.4, 198.9, 147.9, 129.2, 130.2, 134.7, 170.2, 102.5])

In [86]:
# calculer la moyenne par ligne avec axis=1
np.mean(array, axis=1)

array([ 98.55555556, 162.11111111, 181.88888889, 163.        ,
       184.22222222, 142.55555556, 100.        , 176.66666667,
       156.88888889, 184.        ])