In [34]:
# import de la librairie numpy
import numpy as np

In [35]:
# placer le fichier de donnnées houses.csv 
# dans le répertoire de travail de jupyter

# lire le fichier
# nom du fichier, délimiteur utilisé entre les valeurs 
# et préciser le type de données
houses = np.genfromtxt('Houses.csv', delimiter=',', dtype=int)

In [36]:
# prix de vente des maisons américaines en dollars, taille en pieds carré
# colonne 1 : prix de vente de la maison en dollars
# colonne 2 : taille de la maison en pieds carré
# colonne 3 : tailler du terrain en pieds carré
houses

array([[212000,   4148,  25264],
       [230000,   2501,  11891],
       [339000,   4374,  25351],
       [289000,   2398,  22215],
       [160000,   2536,   9234],
       [ 85000,   2368,  13329],
       [ 85000,   1264,   8407],
       [145000,   1572,  12588],
       [164000,   2375,  16204],
       [123500,   1161,   9626],
       [180000,   1542,   8755],
       [159500,   1464,  14636],
       [156000,   2240,  21780],
       [146500,   1269,  11250],
       [101500,    924,   7361],
       [109800,    768,  10497],
       [182000,   1320,  15768],
       [110000,   1845,  12153],
       [125000,   1274,  13634],
       [ 80000,   1905,  10890]])

In [37]:
# 1. convertir le prix des maisons (col1*0.86) de dollars en euros
# première colonne = prix de vente de la maison en dollors
houses[:,0]=houses[:,0] * 0.86
houses

array([[182320,   4148,  25264],
       [197800,   2501,  11891],
       [291540,   4374,  25351],
       [248540,   2398,  22215],
       [137600,   2536,   9234],
       [ 73100,   2368,  13329],
       [ 73100,   1264,   8407],
       [124700,   1572,  12588],
       [141040,   2375,  16204],
       [106210,   1161,   9626],
       [154800,   1542,   8755],
       [137170,   1464,  14636],
       [134160,   2240,  21780],
       [125990,   1269,  11250],
       [ 87290,    924,   7361],
       [ 94428,    768,  10497],
       [156520,   1320,  15768],
       [ 94600,   1845,  12153],
       [107500,   1274,  13634],
       [ 68800,   1905,  10890]])

In [38]:
# 2. convertir les pieds carrés en m2 pour col 2 et 3 : *0.09
# 2.1 Colonne 1 = taille de la maison de pieds carrés à mètre carré
houses[:,1]=houses[:,1] * 0.09
houses

array([[182320,    373,  25264],
       [197800,    225,  11891],
       [291540,    393,  25351],
       [248540,    215,  22215],
       [137600,    228,   9234],
       [ 73100,    213,  13329],
       [ 73100,    113,   8407],
       [124700,    141,  12588],
       [141040,    213,  16204],
       [106210,    104,   9626],
       [154800,    138,   8755],
       [137170,    131,  14636],
       [134160,    201,  21780],
       [125990,    114,  11250],
       [ 87290,     83,   7361],
       [ 94428,     69,  10497],
       [156520,    118,  15768],
       [ 94600,    166,  12153],
       [107500,    114,  13634],
       [ 68800,    171,  10890]])

In [40]:
# 2.2 Colonne 1 = taille du terrain de pieds carrés à mètre carré
houses[:,2]=houses[:,2] * 0.09
houses

array([[182320,    373,   2273],
       [197800,    225,   1070],
       [291540,    393,   2281],
       [248540,    215,   1999],
       [137600,    228,    831],
       [ 73100,    213,   1199],
       [ 73100,    113,    756],
       [124700,    141,   1132],
       [141040,    213,   1458],
       [106210,    104,    866],
       [154800,    138,    787],
       [137170,    131,   1317],
       [134160,    201,   1960],
       [125990,    114,   1012],
       [ 87290,     83,    662],
       [ 94428,     69,    944],
       [156520,    118,   1419],
       [ 94600,    166,   1093],
       [107500,    114,   1227],
       [ 68800,    171,    980]])

In [49]:
# 3. combien de maisons ont un terrain de plus de 1000m2? 
# colonne 3 (index 2)
# appel le array avec des conditions et récupère la taille de l'array 
# respectant cette condition
print(houses[:,2][(houses[:,2] > 1000)])
nbre_maison_plus_1000_m2=len(houses[:,2][(houses[:,2] > 1000)])

print('Nmbre de maisons de plus de 1000 m2 : %d' % nbre_maison_plus_1000_m2)

[2273 1070 2281 1999 1199 1132 1458 1317 1960 1012 1419 1093 1227]
Nmbre de maisons de plus de 1000 m2 : 13


In [58]:
# 4. Calculer la somme totale obtenue après la vente des 20 maisons
# faire la somme de la colonne contenant les prix ==> col 1
col1=houses[:,0]
print(col1)
moyenne_prix_vente=np.mean(col1, axis=0)
print('Moyenne du prix de vente : %f' % moyenne_prix_vente)

# somme totale
somme=np.sum(houses[:,0])
print('Somme totale de la vente des 20 maisons : %d' % somme)


[182320 197800 291540 248540 137600  73100  73100 124700 141040 106210
 154800 137170 134160 125990  87290  94428 156520  94600 107500  68800]
Moyenne du prix de vente : 136860.400000
Somme totale de la vente des 20 maisons : 2737208


In [63]:
# 5. Quelle est la taille de la maison vendue la plus chère?
# utiliser la fonction max quel est le prix la plus chère et
# récupérer la taille

# 5.1 prix de vente le plus cher : prix = col1
prix_le_plus_cher=houses[:,0].max()
print('Prix de vente le plus cher : %d' % prix_le_plus_cher)

# 5.2 récupérer la taille du prix le plus cher 291540 : 93 m2
# récupère la ligne pour laquelle le prix est 291540
ligne_prix_plus_cher=houses[(houses[:,0] == prix_le_plus_cher)]
print(ligne_prix_plus_cher)

# 5.3 récupérer la valeur de la col2 (index 1)
taille_de_maison_plus_cher=houses[(houses[:,0] == prix_le_plus_cher)][:,1]
print('Taille de la maison la plus cher : %d' % taille_de_maison_plus_cher)


Prix de vente le plus cher : 291540
[[291540    393   2281]]
Taille de la maison la plus cher : 393


In [83]:
# 6. Juste pour l'exercice, splitter (casser) l'array en trois tableaux, 
# puis les concaténer à nouveau pour obtenir le tableau initial

# 6.1 spliter le tableau en 3

# SPLIT VERTICAL
# nombre de lignes et colonnes?
print('Taille :', houses.shape)
print('----------------------------------')

# 20 lignes 3 colonnes
print('Index de spit en 3 :', 20/3)
print('----------------------------------')

# 6.66 -- index 6 (colonne 7) puis 13 (colonne 14)
houses1,houses2,houses3=np.split(houses,[6,13])
print('Tableau houses splitté en 3 : solution 1')
print('                                    ')
print(houses1)
print('                                    ')
print(houses2)
print('                                    ')
print(houses3)

# OU

# SPLIT HORIZONTAL
houses4,houses5,houses6=np.hsplit(houses,3)
print('----------------------------------')
print('Tableau houses splitté en 3 : solution 2')
print('                                    ')
print(houses4)
print('                                    ')
print(houses5)
print('                                    ')
print(houses6)

# 6.2 concatener les 3 tableaux splitter en 1 tableau
houses7=np.concatenate([houses1,houses2, houses3])
print('----------------------------------')
print('Tableau reconstitué vertical')
print(houses7)

# ou
houses8=np.concatenate([houses4,houses5, houses6], axis = 1)
print('----------------------------------')
print('Tableau reconstitué horizontal')
print(houses8)



Taille : (20, 3)
----------------------------------
Index de spit en 3 : 6.666666666666667
----------------------------------
Tableau houses splitté en 3 : solution 1
                                    
[[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]]
                                    
[[ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]
 [134160    201   1960]]
                                    
[[125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]
----------------------------------
Tableau houses splitté en 3 : solution 2
                                    
[[182320]
 [197800]
 [291540]
 [248540]
 [137600]
 [ 73100]
 [ 73100]
 [124700]
 [141040]
 [106210]
 [154800]
 [137170]
 [1341